project:
  type: website
  render:
    - manuscript.qmd
    - supplementary.qmd

website:
  navbar:
    left:
      - href: manuscript.qmd
        text: Manuscript
      - href: supplementary.qmd
        text: Supplementary
      - href: https://matcasti.github.io/SPARK-app/
        text: Web-App
    right:
      - icon: github
        href: https://github.com/matcasti/2026-06-BHA-SDE-model/

format:
  html:
    title-block-style: manuscript
    embed-resources: true
    resources: [model_code.R]
    code-links:
      - text: Model (R script)
        href: model_code.R
        icon: file-code
    theme:
      light: Yeti
      dark: Cyborg
    toc: true
  pdf:
    toc: true

bibliography: citations.bib
number-sections: true
date: today
author:
  - name: "Matías Castillo-Aguilar"
    affiliation: "Escuela de Medicina, Universidad de Magallanes, Punta Arenas, Chile."
    orcid: "0000-0001-7291-247X"
  - name: "Noah Beelders"
    affiliation: "Department of Mathematics, University of Munich, Theresienstraße 39, 80333 Munich, Germany."
    orcid: "0000-0001-5953-075X"
  - name: "Diego Mabe-Castro"
    affiliation: "Escuela de Medicina, Universidad de Magallanes, Punta Arenas, Chile."
    orcid: "0000-0002-6663-2153"
  - name: "Cristian Núñez-Espinosa"
    affiliation: "Escuela de Medicina, Universidad de Magallanes, Punta Arenas, Chile."
    orcid: "0000-0002-9896-7062"

